sonar.organization= lucienmathieu03
sonar.projectKey= LUCIENMathieu03_BobApp-OCRM2-P10
sonar.java.binaries= back/target/classes
sonar.sources= front/src, back/src/main/java
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info